### ISSUE TITLE
PreCommit fails

### ISSUE THREAD

**Issue by robov** [smgladkovskiy/phpcs-git-pre-commit#2]
When I run the pre-commits on my windows machine it always fails

When I run the exact same phpcs command in my docker container, the -p flag shows the progress (100%), hence the return value of this command in the bash script does not return 0, so it is interpreted as an error

When I remove the -p the command returns empty, which is good, however the if statement seems not be correct
When I replace the if comparison if  'ne' then it works.
The code below the pre-commit succeeds on a valid phpcs check, and fails on an invalid phpcs check.

```
    ./vendor/bin/phpcs --standard=PSR2 --exclude=Generic.Files.LineLength --extensions=php -n $FILES
    if [ $? ne 0 ]
```

**Comment by smgladkovskiy** [comment]
Hi @robov !

Your are welcome to make a pull request to change code for good reasons! 😉
