### ISSUE TITLE
Adding new branch/openmage-lts support

### ISSUE THREAD

**Issue by sreichel** [smgladkovskiy/phpcs-git-pre-commit#7]
Is it possible to ad a new branch or setup script to make it work out of the box (w/o forking) with https://github.com/OpenMage/magento-lts/issues/982? Magento1/Openmage just needs two sniffs to be excluded by default .... (
` --exclude=Squiz.Classes.ValidClassName,PSR1.Classes.ClassDeclaration`)

Either a new branch (openmage-lts) with a modified hook, or add a new setup-script and a new hook? (`pre-commit.default`, `pre-commit.openmage-lts`) ... or close it :)

**Comment by smgladkovskiy** [comment]
No, I'm sorry. There is no universal in this approach.
