### ISSUE TITLE
I have installed the package but it is not restricting git commit 

### ISSUE THREAD

**Issue by creativedevs** [smgladkovskiy/phpcs-git-pre-commit#9]
I have followed steps and installed package and below command is showing errors

php phpcs.phar --standard=PSR2 --encoding=utf-8 -n -p /path/to/file.php

but why I tried, I have used git bash to commit in winows

git commit -m "" file.php

it does not show error message and stopped committing code

**Comment by smgladkovskiy** [comment]
Hi!

Send me the archive of your project folder (on [email](mailto:smgladkovskiy@gmail.com) or [telegram](https://t.me/smgladkovskiy)). Make sure that the archive contains everything to reproduce the problem (including .git folder).

**Comment by smgladkovskiy** [comment]
I think that issue was resolved as for no reply on my request.
